modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/incorporeal-3/issues"

[[mods]]
modId = "auto_third_person"
version = "${version}"
displayName = "Auto Third Person"
description = "Puts you in third person when you like, get in a boat and stuff."
authors = "quaternary"
credits = "Your mom"

[[dependencies.auto_third_person]]
modId = "minecraft"
mandatory = true
versionRange = "[1.4.7]" # causes recent forges that use mods.toml to explode