plugins {
	id "java"
	id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT"
}

ext.gimmeJava(25)

base {
	archivesName = "${rootProject.name}-fabric-26.1.2"
}

dependencies {
	//Minecraft
	minecraft "com.mojang:minecraft:26.1.2"
	
	//Fabric loader
	implementation "net.fabricmc:fabric-loader:0.19.2"
	
	//Fabric API
	implementation "net.fabricmc.fabric-api:fabric-api:0.149.1+26.1.2"
	
	//Xplat
	implementation project(":Xplat-26.1.2")
	implementation project(":CrummyConfig")
	implementation project(":Core")
}

//fold in xplat resources and sources
processResources {
	from project(":Xplat-26.1.2").sourceSets.main.resources
	from project(":CrummyConfig").sourceSets.main.resources
	from project(":Core").sourceSets.main.resources
}

tasks.withType(JavaCompile) {
	source(project(":Xplat-26.1.2").sourceSets.main.allSource)
	source(project(":CrummyConfig").sourceSets.main.allSource)
	source(project(":Core").sourceSets.main.allSource)
}

//loom doesn't generate run configs by default in subprojects
loom {
	runs {
		client {
			client()
			setConfigName("Fabric 26.1.2 Client")
			ideConfigGenerated(true)
			runDir("./run")
		}
		server {
			server()
			setConfigName("Fabric 26.1.2 Server")
			ideConfigGenerated(true)
			runDir("./run")
		}
	}
}
