name: the real

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Gradle™
        # this version was released 4 days ago at the time of writing (oct 25 2022), and makes Actions
        # be quiet about usage of deprecated things for caching. there will probably be a newer version
        # by the time you read this, maybe even a v3
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build --stacktrace --info

      - name: Upload artifacts™
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs