name: the real

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle™
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace --info

      - name: Upload artifacts™
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            Fabric/build/libs/
            Forge/build/libs/